### ISSUE TITLE
Update alevin-fry and salmon versions

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#181]
**Is your feature request related to a problem? Please describe.**

The current versions that we use for salmon and alevin-fry are a little behind the latest releases. We should update the versions that we are using to reflect the latest changes and updates. 

**Describe the solution you'd like**

Update from Salmon 1.5.2 to[ 1.8.0](https://github.com/COMBINE-lab/salmon/releases/tag/v1.8.0) and from Alevin-fry 0.4.2 to [0.5.0](https://github.com/COMBINE-lab/alevin-fry/releases/tag/v0.5.0).

**Comment by jashapiro** [comment]
I just want to check if this should be blocked by https://github.com/AlexsLemonade/scpca-nf/issues/149? I'm thinking we are okay because we get the salmon version directly from the salmon output, so it is not going to be overwritten in the workflow `meta` object and the final metadata should reflect the version of salmon that was used even if the alevin-fry version differs.  But I want to be sure!
