### ISSUE TITLE
Document sample metadata as input

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#401]
In #400 we are adding the sample metadata file as a parameter to the workflow. We will need to update the external documentation to include the sample metadata that is required. When we do that we will want to note how to fill in the table when sample information is unknown.

**Comment by allyhawkins** [comment]
I was going to get started on this, but I wonder if we want to make the sample metadata optional as input, rather than required? Right now it's required so I wanted to get feelers out there for making it optional before doing this. 

I can imagine scenarios where someone may not have all the sample metadata at the time of processing.
I think the only case where we would want to make sure there is sample metadata is if someone is processing data for contribution to the portal. I think that we could make a note of that in the docs.

I see both sides of this so tagging @jashapiro for any thoughts or opinions.

**Comment by jashapiro** [comment]
I think I am okay if it is required. I think the question that arises is what happens if there is a missing sample or a metadata file with no "data" columns in the sample table (just ids, in other words). I think we would do fine if we are using a left join, right?

So the requirement is that there is a file with the correct headers, not necessarily that it is complete. But ideally, it is complete so all of the sample data makes it into the objects!

**Comment by allyhawkins** [comment]
Yes that should work! I think the question then becomes what are the required columns? 
Should we include all the columns that we have in our sample metadata as "required" even if they are empty?

**Comment by jashapiro** [comment]
I don't think there should be any required columns for the workflow itself except `scpca_sample_id`, as long as the code works. For ourselves and for particular users, we can have specific column requirements.

**Comment by allyhawkins** [comment]
Closed by #467
