### ISSUE TITLE
Add submitter annotations, if available, to SCE objects

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#407]
If submitter annotations are available, we want to create a process to add a column for submitter annotations to the annotated SCE objects. My initial thought is that we would create a process that takes as input a single SCE object and a tsv file containing all the cell type annotations for a single project. This file would include cell barcodes, cell type annotations, and library id. That file will be used to grab the annotations for the specified library. The output from the process will be the annotated SCE object with a new column, `submitted_annotations`. 

The one thing I haven't quite figured out is how we want to read the tsv file into the workflow. I think we want to include the path to the file in the library metadata and then filter to libraries that contain a submitted file. Then, only those libraries would run through the process of adding submitter annotations, but I'm open to other ideas.

**Comment by sjspielman** [comment]
From some Slack conversations:

- To provide TSV to the workflow, we'll add the path to the library metadata file. This way it will be part of the meta object that gets passed along through the workflow with each library.
- We'll add the submitter annotations to the `unfiltered` object, so that users have submitter annotations no matter which object they use
- We can use `NA` for cells the submitter did not even annotate, and `"Unknown"` (string subject to change) for cells that the submitter annotated as unknown/`NA`. This makes the workflow easy as well: convert all submitter `NA` to`"Unknown"` then let`dplyr::left_join()` fill in `NA` for the rest.

**Comment by sjspielman** [comment]
My ZenHub is still acting up, so commenting for now that this is **BLOCKED BY https://github.com/AlexsLemonade/ScPCA-admin/issues/567**

**Comment by sjspielman** [comment]
Closed by #451
