### ISSUE TITLE
Discussion: visualizing SingleR scores in the QC report

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#434]
This issue is opened as a discussion associated with the PR #432 (see https://github.com/AlexsLemonade/scpca-nf/pull/432#issuecomment-1703228407).

We are trying out some different visualization approaches for SingleR scores besides a sina plot with delta median values. One potential approach is to use a ridgeplot, with an `aes` fill of whether the given score is for an assigned cell type or other cell type (see https://github.com/AlexsLemonade/scpca-nf/pull/432#issuecomment-1703195711).

I've taken a first stab at this using the same dataset as in #432. For this, I tried to deal with the fact that ridgeplots can only be made when there are >=3 points in a category, since otherwise the distribution cannot be estimated. 

<img width="713" alt="Screenshot 2023-09-01 at 3 23 41 PM" src="https://github.com/AlexsLemonade/scpca-nf/assets/4701111/6cec4a12-5e76-4e2f-baac-f8d161082ce7">

Here, you can see some rows have no yellow distribution - those are the rows where there are <=2 assigned cells. For those rows I directly added points for where the scores for the assigned cells(s) actually fall. I think this is a cool idea, but I'm not sure about how it came out. 

Anyways, all open for discussion! Tagging @allyhawkins @jaclyn-taroni for now

**Comment by allyhawkins** [comment]
Overall I do like this approach and think that it's more informative than looking at the delta median that we were calculating previously. My only concern is that unlike with `CellAssign`, where the top score will always line up with the predicted cell type, here there is a fine-tuning step that helps assign cells from closely related labels. From the [SingleR book](http://bioconductor.org/books/release/SingleRBook/annotation-diagnostics.html#based-on-the-scores-within-cells): 

> (Note that the assigned label for a cell may not be the visually top-scoring label if fine-tuning is applied, as the only the pre-tuned scores are directly comparable across all labels.)

When I had been looking at the delta median previously, I had labeled the cells that had been fine-tuned and they all had the lower delta medians, which makes sense. I think it would be helpful to overlay that information here because I would anticipate that the cell types with more overlap will have cells that were pruned. But I'm not sure how we would do that without making the plot too busy... I think it may just be worth noting that when we describe the plot, the actual labels go through a fine-tuning step so that the top score may not align with the label. 

> Here, you can see some rows have no yellow distribution - those are the rows where there are <=2 assigned cells. For those rows I directly added points for where the scores for the assigned cells(s) actually fall. I think this is a cool idea, but I'm not sure about how it came out.

I think this is okay. An alternative would just be to show only cell types that have >= 3 cells assigned to begin with.

**Comment by allyhawkins** [comment]
> My worry is that, I agree with you that the ridgeplot is more informative! But, I'm worried I just think it's more informative when really it is not actually very meaningful! It seems true, in general, we'd probably observe higher values for the "labeled as this cell type" vs "all other cells" distributions. But, when looking at these plots, my instinct is to interpret larger differences in distributions to indicate more confident assignments - but that's not what it means!

I think this is a good point. I don't want to lead users into over-interpreting the scores. 

> Given all these SingleR score caveats, I think I'm reticent now to show the raw score distributions at all unless we also show "delta median," which is the only the SingleR book describes as a score to use for "confidence." 

Re-reading the delta median section they do suggest that we use delta scores rather than assignment scores because of sensitivity to technical effects. I think it's fine to keep the delta median approach, but we should label the pruned cells like they do here: 
![image](https://github.com/AlexsLemonade/scpca-nf/assets/54039191/59435679-4214-4683-9843-74952c5faebb)

Also in an ideal world we would make a note about the expected range for "confident" assignments, but I'm not sure there is one. This is all they say: 
> Labels with especially low deltas may warrant some additional caution in their interpretation.

**Comment by sjspielman** [comment]
Now that #432 is all set we can close this discussion issue.
