### ISSUE TITLE
Ensure SingleR exports a TSV file

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#462]
From #446:

> In doing this we will want a way to track the reference versions used for both cell typing methods and only skip when both the output files exist and the reference version matches.

Currently, it's not easy to track whether `SingleR` has been run, since the cell type annotations are directly added into the SCE object. We should update `SingleR` cell typing to first export a TSV file, and then add those contents into the SCE in a second step.

At first, I saw two ways we could do this:
- Add another argument to `classify_SingleR.R` with the TSV file to export
- Create a separate process that first performs cell typing and exports a TSV. Then, have a process which runs an R script to add that information into the SCE object.

I was originally thinking to do the first option, since it's very simple! But, the second option has the benefit of mirroring how we handle `CellAssign`. That said, a whole process for just reading a TSV file and adding to colData seems like a lot of unnecessary S3 file transfers.

So, now I'm thinking we still have two _scripts_ (make a TSV and then add to SCE), but call them _both_ from the same process:
- The process should keep the same name `classify_singleR`
- Then, this process will call two scripts: `classify_SingleR.R` which will export a TSV file of annotations, and `annotate_SingleR.R` which will add to SCE

Moreover, maybe we should take this opportunity and do the same with `CellAssign` before porting things over into `main.nf`. For this, we could have a single process called `classify_cellassign` that runs two scripts: `predict_cellassign.py` and then `annotate_cellassign.R`. Since `CellAssign` takes such a long time, any small time/memory savers like this can't hurt. One change we'd need to make is, we'd have to pass `classify_singler.out` into the `classify_cellassign` process to ensure everything makes it into the same SCE.

Edit: bonus, we probably could use the same R script for add annotations from a TSV, using arguments and `if`s to handle the differences. Give it a general name like `add_annotations_to_sce.R`.

Tagging folks for discussion! @allyhawkins @jashapiro

**Comment by jashapiro** [comment]
I'm not sure I understand the use case, but if we just want to track whether SingleR has been performed for the purposes of the workflow, the easiest way would be to add a metadata field (`meta.has_singler` or something similar). Combining the CellAssign steps into a single process does make some sense to me, but if we are not planning to use the tsv file for anything, I don't think there is any reason to make it.

**Comment by sjspielman** [comment]
Thanks for the feedback, @jashapiro! Context, this issue came from a brief chat I had had with @allyhawkins early last week about getting a TSV file for SingleR as a check for whether we've performed cell typing, so this issue was expanding on that with next steps.

But, definitely simpler to have just a metadata field as true/false which could be added at the top of the workflow and modified once cell type annotation is performed. To my knowledge there is no plan to disseminate/use TSV files at all besides as an intermediate stage to get them into SCEs (needed for CellAssign since python).

I remain a fan of one process for CellAssign though, ngl in part because I am always confused by which of it's two processes if which..!

**Comment by jashapiro** [comment]
> But, definitely simpler to have just a metadata field as true/false which could be added at the top of the workflow and modified once cell type annotation is performed.

You don't even need it to be added at the top of the workflow. If `meta.has_singler` is not defined, it will be treated as `false` in any logical statement.

**Comment by allyhawkins** [comment]
My original thought process here was just to modify `classify_singleR` to output a TSV instead of an SCE object. Then add the tsv file as an additional input to the already existing process for adding the cell type annotations to the SCE object for `CellAssign`, `classify_cellassign`. It would probably need to be renamed since it would be used to incorporate both the `CellAssign` and `singleR` output into the object. But no new processes would need to be created. 

However, if we can just add a value stating whether or not the cell type annotations exist then that seems easier. A question I have though is about where this is going in the workflow? I would imagine that cell typing will be the last step in the workflow. So let's say you're running the workflow for the first time, you will get an `scpca-meta.json` that gets stored in the `checkpoints` folder after mapping. This `scpca-meta.json` will not have the `has_singler` or `has_cellassign`. You will also get a `scpca-meta.json` in the `results` folder and that will have the cell typing meta fields. 

Now, you go to run the workflow again and re-process an object. That will start by loading in the `scpca-meta.json` from the `checkpoints` folder that doesn't have the cell typing fields. This means if cell typing already exists then we wouldn't have a way to know that and it would repeat it. Unless you are planning on reading the `scpca-meta.json` from the `results` folder? But we haven't done that before.

**Comment by sjspielman** [comment]
> Now, you go to run the workflow again and re-process an object. That will start by loading in the `scpca-meta.json` from the checkpoints folder that doesn't have the cell typing fields.

Maybe for these situations we can just always remember to do a `--repeat_celltyping` flag?

**Comment by allyhawkins** [comment]
> Cell typing isn't the last step in the workflow though, is it? That is always the QC report, I thought.
> 
> So we would look in checkpoints for the output of the second cell typing step, whichever that is (presumably Cell Assign). From there we look for `has_singler` and `has_cellassign` which are either `true` or not present (interpreted by groovy as `false`). We also check the version of the reference.
> 
> If the cell assign output folder does not exist in checkpoints, then we are also going to run cell typing, as we do for other steps, so I don't think we have to remember to use the repeat flag.

I think the problem with this though is that whenever you run the workflow, it reads in the `scpca-meta.json` from the `checkpoints/rad` folder and then it exports that `scpca-meta.json` in the next steps. So it doesn't matter where cell typing is in the workflow, if it's after mapping then were going to overwrite it. Every time we start from the metadata that doesn't have it, it gets over-written. 

> Maybe for these situations we can just always remember to do a --repeat_celltyping flag?

This also wouldn't matter here because `--repeat_celltyping` would tell the workflow to repeat it no matter what previous files exist. We don't want to do that.

**Comment by jashapiro** [comment]
> I think the problem with this though is that whenever you run the workflow, it reads in the `scpca-meta.json` from the `checkpoints/rad` folder and then it exports that `scpca-meta.json` in the next steps. So it doesn't matter where cell typing is in the workflow, if it's after mapping then were going to overwrite it. Every time we start from the metadata that doesn't have it, it gets over-written.
> 

Oh, yes, we would have to read the file from a later checkpoint folder! (and presumably fall back to the `rad` file version if a later file doesn't exist).

**Comment by jashapiro** [comment]
Following up again: We shouldn't need to read a different file in the initial meta loading: we can check the updated metadata for later steps as we do here for whether we want to do the demux steps again: 
https://github.com/AlexsLemonade/scpca-nf/blob/d248edbf8adee1e68d6858804ca722d6499f1d03/modules/genetic-demux.nf#L21C1-L21C1

**Comment by sjspielman** [comment]
This was essentially accomplished in re-orgs done in #477 and #478.
