### ISSUE TITLE
Add more context to supplemental celltypes report

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#489]
In #483, we've started the separate celltype QC report. We'll want to beef this up a little with more textual explanations.

**Comment by sjspielman** [comment]
🌶️ Link that news you can use paper above every UMAP.

**Comment by jaclyn-taroni** [comment]
@jashapiro @sjspielman @allyhawkins If you'd like to weigh in asynchronously, please do so by EOD on the 16th. We'll meet on the 17th for a synchronous discussion.

**Comment by sjspielman** [comment]
Here's the current version of the report! 
(Note that cluster values were simulated for report development, so don't worry about how heatmaps comparing to clusters look)
[celltypes_supplemental_report.html.txt](https://github.com/AlexsLemonade/scpca-nf/files/12859496/celltypes_supplemental_report.html.txt)

**Comment by allyhawkins** [comment]
Some initial thoughts I have on what we may want to include in the report to help with our discussion later:
- It's probably worth repeating some of the information that's going to be in the main report cell type section. How much repetition is probably something we should talk about, but I think the intro should include some information on which cell type annotation methods were included and if there are also submitter annotations. 
- On that same note, I think it might also be worth repeating the information about the references that were used. 
- I also think we should maybe add a note about looking for consistency in cell type annotations across the methods. Right now, we tell them to look for high delta median and high probabilities, but I think we should note that those metrics are somewhat arbitrary and that comparing annotations directly across methods is going to be helpful. 
- In regards to repetition... I do think it would be helpful to include some sort of reference for what cell types are represented for each method used. Specifically, I do think we should include the UMAPs for cell types and clusters in the supplemental and main report. I don't really like having to switch back and forth between the two to look at the UMAP, and personally, I would want to be able to look at all the data we are presenting to make an informative decision about cell types.

**Comment by jaclyn-taroni** [comment]
Can we get a current version of the main report that includes the cell type section as well, please?

**Comment by allyhawkins** [comment]
I just generated this one with one of the libraries we have been using for testing. 

[main_qc_report.html.zip](https://github.com/AlexsLemonade/scpca-nf/files/12885523/main_qc_report.html.zip)

**Comment by jashapiro** [comment]
Looking at the current report, here are my thoughts, in bullet form

* Bullets are good: we have a lot of long text, which is informative but hard to digest quickly
* I think we want a general introduction, briefly describing the cell typing methods we are using and maybe a bit about why we are using them
	* something about the references being used?

* We should include the UMAPs and cell type counts in this report as well as the main report (I see that Ally said this too)

* SingleR/delta median:
  * I think this section has all the information I think we want to convey, but the long paragraphs may make the important points harder to pull out for someone coming in. Some resturcturing might help
  * I would maybe start with a more direct statement along the lines of "We evaluate the quality of SingleR cell type assignments by comparing the score for the top cell type to the median score for other cell types." Then explain what the score actually is.
  * Minor, but we might want to change/reverse the colors? The brighter blue seems an odd choice for the cells that were "rejected". I'd maybe go with a grey for those?
  * We might flip the axes to make reading the cell types easier?
 
* CellAssign probabilities
  * Here too I think we want a bit more emphasis on the value being displayed, rather than starting as a description of what the method calculates. (In this case they are the same thing, but phrasing could emphasize the score first)
  * I think we can drop the median bars: I don't think they are providing much information.
  * Similarly, if we never see the "Cell assigned as a given cell type" being much different from zero, we might just  not show those? (Minor pet peeve of seeing density plots with negative probability values, or values greater than 1)
  * If we just show the probabilities for the "assigned" cells, we could make them scatter/sina plots? That might allow a more parallel plot to the SingleR plot, and have the benefit of a visual representation of how many cells are in each classification


* Heatmaps
  * This section is where I think we want more scaffolding: What kinds of patterns should users expect to see if cell typing is reliable?
  * My preference would be to _not_ use hierarchical clustering for these plots, as I think it makes comparing among plots more challenging. We should try to keep order consistent among all plots
  * I might also move row labels to the left for easier reading

**Comment by jaclyn-taroni** [comment]
I don't have too much to add in the way of "big ideas" that haven't already been covered, so I'll start by adding some minor things I saw:

* Add citations for both methods
* `CellAssign` ridge plot seems to still be a bit cutoff at the very top
* SingleR language in paragraph ("low quality" and "high quality") differs from the plot labeling, so we might benefit from making that a little more cohesive
* We say "Again, different annotations may use different names for similar cell types." in the submitter annotation comparison section. I expect that might be leftover from the pre-supplemental report days?

And bigger things that haven't been explicitly mentioned yet:

* Really need to talk about why we're comparing to clustering and remind people how clustering was performed in the heatmaps sections
* Is the total number of cells overlapping for sure what we want to show in the heatmaps? Are we more interested in some measure of similarity? I'm not sure either way and would like to discuss.
* What does a _bad_ `CellAssign` plot look like? (I think this relates to what Josh is getting at, but see my next point below.)

Different opinions from what have been posted:

* I think plots that are similar in format when you're showing different metrics can be dangerous. Having different plot types might be "good friction."

**Comment by allyhawkins** [comment]
I'm going to close this since we have broken this out into multiple issues that are being addressed.
